### ISSUE TITLE
Comments don't load

### ISSUE THREAD

**Issue by NSExceptional** [carson-katri/reddit-swiftui#13]

**Comment by carson-katri** [comment]
Could you please provide more information?
I'd like to know which platform, and also information as to which post you were attempting to view.

**Comment by NSExceptional** [comment]
macOS 10.15

Any post

**Comment by carson-katri** [comment]
I am unable to replicate this with a fresh clone and Xcode 11.3.1, macOS 10.15.3 beta 2.
