### ISSUE TITLE
Xcode Build Fail - MacOS

### ISSUE THREAD

**Issue by syddo** [carson-katri/reddit-swiftui#14]
I get this error:

Showing Recent Issues
No account for team "FH9CW55WY5". (Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.)

**Comment by carson-katri** [comment]
Try switching the team for signing in the project settings to your Apple ID in that drop down box (should be visibly red since the team is wrong).

**Comment by syddo** [comment]
Thanks! this is okay now.
closing the issue here.
