### ISSUE TITLE
[Help] to Work on my machine and I contributo to project!

### ISSUE THREAD

**Issue by mauriliofilho** [carson-katri/reddit-swiftui#17]
[HELP] i need help to branch oauth work on my machine, i get error when o compile project, error in Request not found!

**Comment by carson-katri** [comment]
Which file is the error occurring in?

**Comment by mauriliofilho** [comment]
![image](https://user-images.githubusercontent.com/1377303/83701510-35144680-a5e0-11ea-8ad3-5dba48a89936.png)

the error is this! only occourer in branch oauth, in master is build ok!

**Comment by carson-katri** [comment]
Try File > Swift Packages > Update to Latest Package Versions

**Comment by mauriliofilho** [comment]
> Try File > Swift Packages > Update to Latest Package Versions

This not work here, stay with same error!!

**Comment by carson-katri** [comment]
I have found the issue. You can either pull the newest commit or to fix it quickly:

Click on the project in the Project navigator, then select "Swift Packages". Double click on `swift-request` and change the rules to Version -> Up to Next Major -> `1.2.2`. This should resolve the issue.
