### ISSUE TITLE
TestFlight

### ISSUE THREAD

**Issue by AustinConlon** [carson-katri/reddit-swiftui#4]
I'd be interested in testing this out through TestFlight. An email invite (austinconlon@icloud.com) would be wonderful, and/or you could generate a public TestFlight link and put it on the repository.

**Comment by carson-katri** [comment]
I am unable to upload binaries that use iOS 13 features until the GM seed of Xcode 11 is released. I'm closing this for now and may reopen once that's available.

**Comment by AustinConlon** [comment]
That’s just for shipping to the public App Store.

**Comment by AustinConlon** [comment]
https://reddit.com/r/iOSProgramming/comments/cqdqe8/is_it_possible_to_distribute_ios_13_apps_to/

**Comment by carson-katri** [comment]
Huh. Thanks for the info. I tried uploading when you asked initially and got some errors for using combine and SwiftUI. I’ll try it again

**Comment by AustinConlon** [comment]
Gotcha. I was just listening to a podcast where someone said they were experiencing distribution issues with Catalyst, filed it in Feedback Assistant, then an Apple employee responded saying it wasn’t intended behavior. I’d file one too, maybe they’ll provide a workaround.

**Comment by AustinConlon** [comment]
https://twitter.com/ryanashcraft/status/1163933169030033408?s=21

**Comment by carson-katri** [comment]
Sorry for the wait. The build was rejected for the following reasons: 

4. 1 Design: Copycats
5. 2.5 Legal: Intellectual Property - Apple Products

The first is due to my metadata “leveraging Reddit” and the second because my apps metadata says stuff about SwiftUI. Once I fix these issues it should be available.

**Comment by Benetos** [comment]
Any updates? would love to check it out...

**Comment by carson-katri** [comment]
@Benetos Sorry there hasn't been any progress. I've been pretty busy, but I'll try to get a build uploaded and submitted for review tonight.

**Comment by Benetos** [comment]
I get it and no worries, would love to test it though. Also I sent you an
email about a Xcode question if you get a chance to check it out

**Comment by carson-katri** [comment]
The public beta is now available: https://testflight.apple.com/join/oiQDuLT7
The link has also been added to the README!
