### ISSUE TITLE
[macOS] Clicking on the post list text, the NavigationLink isn't triggered

### ISSUE THREAD

**Issue by SirArkimedes** [carson-katri/reddit-swiftui#9]
**What happens:**
When clicking on any of the text, or elements, that are in the List on macOS, the NavigationLink destination isn't triggered.

An example:
When clicking on the text that is enclosed within the red box,
<img width="383" alt="macOS" src="https://user-images.githubusercontent.com/3119506/67151764-3aa26380-f27f-11e9-8a37-a6f36825da7d.png">
The `PostDetailView` destination does not get triggered.
The only way to trigger the `PostDetailView` is to click outside of the Text elements.

**Additional details:**
Removing the `.onTapGesture(count: 2)` from macOS' `PostView` will allow the clicks to be passed through again. Though, this obviously removes the double click to open a new window functionality.

**Comment by banaslee** [comment]
Was looking at this issue since it was the first thing I noticed when trying the app out.
Tried ```.allowsHitTesting(false)``` on ```PostView``` and also ended up disabling the double tap.

I believe the ```NavigationLink``` is cancelling any other gesture but I was not able to prevent that.

This is my first look at SwiftUI, so I'm not sure it's even possible to reproduce the ```NavigationLink``` behaviour.

**Comment by banaslee** [comment]
Actually, just discovered the double tap only works on top of the labels (where now the tap is not detected). Wanted to add that since I didn't see in the bug description.

**Comment by banaslee** [comment]
Gave it another try, went a bit deeper and I have a proposal. Only side effect is that cells now don't get a selected state
